import os
import subprocess
import requests

"""
3. Modify PR Agent to Check Tests

Your PR agent should only create PR if tests pass.
"""


def pr_agent(state):

    test_output = state["test_output"]
    repo_url = state["repo_url"]
    local_repo_path = state["local_repo_path"]

    if "failed" in test_output.lower():
        return {"status": "tests failed, PR not created"}

    branch = "ai-fix-branch"

    # ensure local repo is uptodate.
    subprocess.run(["git", "checkout", "main"], cwd=local_repo_path)
    subprocess.run(["git", "pull", "origin", "main"], cwd=local_repo_path)

    subprocess.run(["git", "checkout", "-b", branch], cwd=local_repo_path)

    # stage changes
    subprocess.run(["git", "add", "."], cwd=local_repo_path)

    # commit
    subprocess.run(["git", "commit", "-m", "AI fix"], cwd=local_repo_path)

    # push to fork
    subprocess.run(
        ["git", "push", "--set-upstream", "origin", branch], cwd=local_repo_path
    )

    repo = repo_url.replace("https://github.com/", "").replace(".git", "")

    owner, repo_name = repo.split("/")

    github_token = os.getenv("GITHUB_TOKEN")
    github_user = os.getenv("GITHUB_USER")

    pr_api = f"https://api.github.com/repos/{owner}/{repo_name}/pulls"

    headers = {
        "Authorization": f"Bearer {github_token}",
        "Accept": "application/vnd.github+json",
    }

    data = {
        "title": "AI Generated Fix",
        "body": "Automated fix generated by AI agent",
        "head": f"{github_user}:{branch}",
        "base": "main",
    }

    response = requests.post(pr_api, headers=headers, json=data)

    # Check if request was successful
    if response.status_code == 201:
        pr_url = response.json().get("html_url", "PR created but URL not available")
        print("✅ PR Agent - Completed")
        return {"status": "PR created", "pr_url": pr_url}
    else:
        error_msg = response.json().get("message", "Unknown error")
        print(f"GitHub API response: {response.status_code} - {error_msg}")

        # If PR already exists
        if "already exists" in error_msg.lower() or response.status_code == 422:
            existing_pr_url = f"https://github.com/{owner}/{repo_name}/pulls"
            return {"status": "PR already exists", "pr_url": existing_pr_url}

        # If branch was pushed, provide compare URL for manual PR
        compare_url = (
            f"https://github.com/{owner}/{repo_name}/compare/ai-fix-branch?expand=1"
        )
        print("✅ PR Agent - Completed")
        return {"status": f"PR creation failed: {error_msg}", "pr_url": compare_url}


"""

Why specifically?
API Requirements: The GitHub API endpoint for managing pull requests looks like this: https://api.github.com/repos/{owner}/{repo_name}/pulls. 
It doesn't want the full URL; it only wants the owner/repo_name segment (the "slug").

Removing "Noise": * replace("https://github.com/", "") removes the protocol and domain prefix.

replace(".git", "") removes the file extension, which is technically part of the clone URL but not part of the repository's identity in the API.

"""


"""
Parsing the Repository: It takes a standard GitHub URL (e.g., https://github.com/user/project.git) and extracts the owner and repo_name needed to address the API.

Authentication: It pulls a GITHUB_TOKEN from your environment variables. This token acts as your "digital ID," giving the script permission to act on your behalf.

Configuring the PR: It builds a JSON object (data) containing:

Title/Body: The labels for the PR.

Head: The branch where your AI agent made its changes (e.g., your-username:fix-branch).

Base: The target branch where the code should be merged (usually main).

API Call: It sends a POST request to GitHub's PR endpoint. If successful, GitHub creates the PR, and the function returns the URL for the newly created PR.

"""
